#!/bin/env bash

utils_dir="$(readlink -f $0 | xargs dirname)/../utils/"

echo 'perform mass erase'
${PLATFORM_DIR}/mass_erase
echo 'mass erase done'
if ${utils_dir}/mcu_ping
then
    exit 1
else
    exit 0
fi
