#!/bin/env bash

uptime1=$(curl -s https://${BLYNK_SERVER}/external/api/get?token=${BLYNK_AUTH_TOKEN}\&v2)
sleep 3
uptime2=$(curl -s https://${BLYNK_SERVER}/external/api/get?token=${BLYNK_AUTH_TOKEN}\&v2)
if [ "${uptime1}" = "${uptime2}" ]
then
   exit 1
else
   exit 0
fi
