#!/bin/env bash

utils_dir="$(readlink -f $0 | xargs dirname)/../utils"
board_dir="$(readlink -f $0 | xargs dirname)/../boards/${BOARD}"

if [ -z ${PRJDIR+x} ]; then PRJDIR=${PWD}; fi

${utils_dir}/set_src_creds

v="$((RANDOM % 128)).$((RANDOM % 128)).$((RANDOM % 128))"
echo "building version ${v}"
${utils_dir}/set_src_ver ${v}
cd ${PRJDIR}/${SAMPLE_PATH}
./build.sh ${BOARD}
cd - &>> /dev/null
echo "building done"

echo "flash board"
${board_dir}/flash_board
echo "flash done"

if ${utils_dir}/wait_online 50 5 && ${utils_dir}/wait_mcu_ping 10 5
then
    exit 0
else
    exit 1
fi
