name: build

on:
  push:
    paths-ignore: ['**.md', '**.svg', '**.png']

jobs:
  build:
    name: Build (${{ matrix.zephyr_ver }}, ${{ matrix.sample.board }})
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        zephyr_ver: ["v3.5.0", "main"]
        sample:
        - { board: nucleo_l4r5zi,                   path: samples/basic,        toolchains: arm-zephyr-eabi }
        - { board: nucleo_f746zg,                   path: samples/basic,        toolchains: arm-zephyr-eabi }
        - { board: nucleo_f767zi,                   path: samples/basic,        toolchains: arm-zephyr-eabi }
        - { board: adafruit_feather_stm32f405,      path: samples/basic,        toolchains: arm-zephyr-eabi }
        - { board: blackpill_f411ce,                path: samples/basic,        toolchains: arm-zephyr-eabi }
        - { board: rpi_pico,                        path: samples/basic,        toolchains: arm-zephyr-eabi }
        - { board: stm32f072b_disco,                path: samples/basic,        toolchains: arm-zephyr-eabi }
        - { board: adafruit_feather_m0_basic_proto, path: samples/without_ota,  toolchains: arm-zephyr-eabi }
        - { board: arduino_uno_r4_minima,           path: samples/without_ota,  toolchains: arm-zephyr-eabi }
        exclude:
          - zephyr_ver: "v3.5.0"
            sample: { board: arduino_uno_r4_minima }

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Zephyr
        uses: khrystynaO/zephyr-setup@main
        with:
          manifest-file: tests/west_${{ matrix.zephyr_ver }}.yaml
          toolchains: ${{ matrix.sample.toolchains }}
      - name: Build ${{ matrix.sample.path }}
        run: |
          echo "ZEPHYR_BASE=${ZEPHYR_BASE}"
          echo -n "Zephyr OS: "; git -C $ZEPHYR_BASE --no-pager log --abbrev-commit --pretty=oneline -1
          cd ${{ matrix.sample.path }}
          echo 'CONFIG_BLYNK_TEMPLATE_ID="TMPLxxxxxxxxx"' >> prj.conf
          echo 'CONFIG_BLYNK_TEMPLATE_NAME="Test Device"' >> prj.conf
          ./build.sh ${{ matrix.sample.board }}

