name: build

on:
  push:
    paths-ignore: ['**.md', '**.svg', '**.png']
  pull_request:
    paths-ignore: ['**.md', '**.svg', '**.png']

jobs:
  build:
    name: Build (latest)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      BOARD: blackpill_f411ce

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Setup Zephyr
        uses: khrystynaO/zephyr-setup@main
        with:
          zephyr-version: v3.5.0
          toolchains: arm-zephyr-eabi
      - name: Set Blynk ID and Name
        run: |
          cd samples/basic
          echo 'CONFIG_BLYNK_TEMPLATE_ID="TMPL4V9okroD9"' >> prj.conf
          echo 'CONFIG_BLYNK_TEMPLATE_NAME="LED ESP32"' >> prj.conf
      - name: Build
        run: |
          cd samples/basic
          ./build.sh ${BOARD}

