name: build

on:
  push:
    paths-ignore: ['**.md', '**.svg', '**.png']
  pull_request:
    paths-ignore: ['**.md', '**.svg', '**.png']

jobs:
  build:
    name: Build (latest)
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      BOARD: blackpill_f411ce

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Zephyr
        uses: fabiobaltieri/zephyr-setup@main
        with:
          app-path: samples/basic
          toolchains: arm-zephyr-eabi
      - name: Build
        run: |
          west build -p -b ${BOARD} --sysbuild . -- \
            -Dmcuboot_DTC_OVERLAY_FILE=$(pwd)/boards/${BOARD}.overlay \
            -Dmcuboot_EXTRA_DTC_OVERLAY_FILE=${ZEPHYR_BASE}/../bootloader/mcuboot/boot/zephyr/app.overlay \
            -DEXTRA_CONF_FILE=$(pwd)/boards/witty_cloud.conf
